const orderTypes = {
  CREATE_ORDER_START: "CREATE_ORDER_START",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAIL: "CREATE_ORDER_FAIL",
  ORDER_DETAIL_START: "ORDER_DETAIL_START",
  ORDER_DETAIL_SUCCESS: "ORDER_DETAIL_SUCCESS",
  ORDER_DETAIL_FAIL: "ORDER_DETAIL_FAIL",
  
}
export default orderTypes
