const productsTypes = {
    FETCH_PRODUCTS_START : "FETCH_PRODUCTS_START",
    FETCH_PRODUCTS_SUCCESS:"FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAIL:"FETCH_PRODUCTS_FAIL",
    REMOVE_PRODUCT_START : "REMOVE_PRODUCT_START",
    REMOVE_PRODUCT_SUCCESS : "REMOVE_PRODUCT_SUCCESS",
    REMOVE_PRODUCT_FAIL : "REMOVE_PRODUCT_FAIL",
    FETCH_MYADMIN_PRODUCTS:"FETCH_MYADMIN_PRODUCTS"
}

export default productsTypes