const productsTypes = {
    FETCH_PRODUCTS_START : "FETCH_PRODUCTS_START",
    FETCH_PRODUCTS_SUCCESS:"FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAIL:"FETCH_PRODUCTS_FAIL"
}

export default productsTypes