const userProfilTypes = {
  USER_GET_PROFILE_START: "USER_GET_PROFILE_START",
  USER_GET_PROFILE_SUCCESS: "USER_GET_PROFILE_SUCCESS",
  USER_GET_PROFILE_FAIL: "USER_GET_PROFILE_FAIL",

  USER_UPDATE_PROFILE_FAIL: "USER_UPDATE_PROFILE_FAIL",
  USER_UPDATE_PROFILE_START: "USER_UPDATE_PROFILE_START",
  USER_UPDATE_PROFILE_SUCCESS: "USER_UPDATE_PROFILE_SUCCESS",
  USER_PROFILE_RESET: "USER_PROFILE_RESET",
}
export default userProfilTypes
