const topProductTypes = {
  FETCH_TOP_PRODUCTS_SUCCESS: "FETCH_TOP_PRODUCTS_SUCCESS",
  FETCH_TOP_PRODUCTS_FAIL: "FETCH_TOP_PRODUCTS_FAIL",
  FETCH_TOP_PRODUCTS_START: "FETCH_TOP_PRODUCTS_START",
}

export default topProductTypes
