const orderPayTypes = {
  ORDER_PAY_START: "ORDER_PAY_START",
  ORDER_PAY_SUCCESS: "ORDER_PAY_SUCCESS",
  ORDER_PAY_FAIL: "ORDER_PAY_FAIL",
  ORDER_PAY_RESET: "ORDER_PAY_RESET",
}
export default orderPayTypes
