const productTypes = {
    FETCH_PRODUCT_START : "FETCH_PRODUCT_START",
    FETCH_PRODUCT_SUCCESS:"FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_FAIL:"FETCH_PRODUCT_FAIL",
    CREATE_NEW_PRODUCT : "CREATE_NEW_PRODUCT",
    UPDATE_PRODUCT : "UPDATE_PRODUCT",
    CLEAR_PRODUCT : "CLEAR_PRODUCT", 
}

export default productTypes