const getLogedInUserOrdersTypes = {
  GET_LOGED_IN_USER_ORDERS_START: "GET_LOGED_IN_USER_ORDERS_START",
  GET_LOGED_IN_USER_ORDERS_SUCCESS: "GET_LOGED_IN_USER_ORDERS_SUCCESS",
  GET_LOGED_IN_USER_ORDERS_FAIL: "GET_LOGED_IN_USER_ORDERS_FAIL",
  GET_ADMIN_ORDERS_SUCCESS:"GET_ADMIN_ORDERS_SUCCESS",
  REMOVR_ORDER:"REMOVR_ORDER"
}
export default getLogedInUserOrdersTypes