const getLogedInUserOrdersTypes = {
  GET_LOGED_IN_USER_ORDERS_START: "GET_LOGED_IN_USER_ORDERS_START",
  GET_LOGED_IN_USER_ORDERS_SUCCESS: "GET_LOGED_IN_USER_ORDERS_SUCCESS",
  GET_LOGED_IN_USER_ORDERS_FAIL: "GET_LOGED_IN_USER_ORDERS_FAIL",
}
export default getLogedInUserOrdersTypes