const adminTypes = {
  GET_USER_LIST_START: "GET_USER_LIST_START",
  GET_USER_LIST_SUCCESS: "GET_USER_LIST_SUCCESS",
  GET_USER_LIST_FAIL: "GET_USER_LIST_FAIL",
  REST_ADMIN: "REST_ADMIN",
  REMOVE_USER_FROM_DATA : "REMOVE_USER_FROM_DATA",
  REMOVE_USER_FAIL: "REMOVE_USER_FAIL",
  GET_USER_PROFILE_START_FOR_ADMIN :"GET_USER_PROFILE_START_FOR_ADMIN",
  GET_USER_PROFILE_SUCCESS_FOR_ADMIN :"GET_USER_PROFILE_SUCCESS_FOR_ADMIN",
  GET_USER_PROFILE_FAIL_FOR_ADMIN :"GET_USER_PROFILE_FAIL_FOR_ADMIN",

}
export default adminTypes
